block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
evaluate-variables: true
external-checks-dir:
  - ./policies
external-modules-download-path: .external_modules
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_158
  - CKV_AWS_338
skip-path:
  - ^.*/packages(/.*)?$
summary-position: top
